# Generated by Django 5.2.12 on 2026-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='last_ticket_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
