# Generated by Django 5.2.12 on 2026-04-05 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('queues', '0002_queue_last_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='companies.branch', verbose_name='Филиал'),
        ),
    ]
