# Generated by Django 5.2.12 on 2026-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_alter_queue_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на очередь'),
        ),
    ]
