# Generated by Django 5.2.12 on 2026-04-05 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_queue_queue_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='clients_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит клиентов в очереди'),
        ),
        migrations.AddField(
            model_name='queue',
            name='notification_options',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Настройки уведомлений'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='enqueued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время постановки в очередь'),
        ),
    ]
