# Generated by Django 5.2.12 on 2026-04-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_queue_clients_limit_queue_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('IN_SERVICE', 'In Service'), ('LEFT', 'Left'), ('NOT_ARRIVED', 'Not Arrived')], default='WAITING', max_length=20, verbose_name='Статус'),
        ),
    ]
