# Generated by Django 5.2.12 on 2026-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_ticket_initial_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='called_ticket_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Таймаут вызванного талона (сек)'),
        ),
        migrations.AddField(
            model_name='queue',
            name='language',
            field=models.CharField(default='ru', max_length=10, verbose_name='Язык очереди'),
        ),
        migrations.AddField(
            model_name='queue',
            name='poster_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок плаката'),
        ),
        migrations.AddField(
            model_name='queue',
            name='poster_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок плаката'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('IN_SERVICE', 'In Service'), ('LEFT', 'Left'), ('NOT_ARRIVED', 'Not Arrived'), ('REMOVED', 'Removed')], default='WAITING', max_length=20, verbose_name='Статус'),
        ),
    ]
