# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_queue_called_ticket_timeout_seconds_queue_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время вызова'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала обслуживания'),
        ),
    ]
