# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_ticket_called_at_ticket_service_started_at'),
        ('users', '0006_user_assigned_queues_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='operator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='processed_tickets',
                to='users.user',
                verbose_name='Ответственный оператор',
            ),
        ),
    ]
