# Generated by Django 5.2.12 on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('queues', '0007_ticket_initial_ticket_number'),
        ('users', '0005_admintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEEDBACK', 'Feedback'), ('COMPLAINT', 'Complaint')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='companies.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='companies.company', verbose_name='Компания')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='queues.queue', verbose_name='Очередь')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback_items', to='users.user', verbose_name='Кем обработано')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ('-created_at',),
            },
        ),
    ]
