# Generated by Codex on 2026-05-07

import django.db.models.deletion
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('queues', '0010_ticket_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackitem',
            name='rating',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name='Оценка обслуживания',
            ),
        ),
        migrations.AddField(
            model_name='feedbackitem',
            name='ticket',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='feedback_items',
                to='queues.ticket',
                verbose_name='Талон',
            ),
        ),
    ]
