# Generated by Codex on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_queue_token'),
        ('companies', '0001_initial'),
        ('notifications', '0002_feedbackitem_rating_feedbackitem_ticket'),
        ('queues', '0010_ticket_operator'),
        ('users', '0006_user_assigned_queues_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WEB_PUSH', 'Web push'), ('VK', 'VK')], max_length=20, verbose_name='Канал')),
                ('endpoint', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Web push endpoint')),
                ('p256dh_key', models.TextField(blank=True, null=True, verbose_name='Web push p256dh')),
                ('auth_key', models.TextField(blank=True, null=True, verbose_name='Web push auth')),
                ('vk_user_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='VK ID')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='clients.client', verbose_name='Клиент')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notification_subscriptions', to='queues.queue', verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('target_url', models.URLField(max_length=1000, verbose_name='URL вебхука')),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Секрет подписи')),
                ('event_types', models.JSONField(blank=True, default=list, verbose_name='Типы событий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='companies.company', verbose_name='Компания')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhook_subscriptions', to='users.user', verbose_name='Кем создана')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='queues.queue', verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Webhook-подписка',
                'verbose_name_plural': 'Webhook-подписки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WEB_PUSH', 'Web push'), ('VK', 'VK')], max_length=20, verbose_name='Канал')),
                ('event_type', models.CharField(choices=[('ticket.called', 'Ticket called')], max_length=50, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='queues.queue', verbose_name='Очередь')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.clientnotificationsubscription', verbose_name='Подписка')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='queues.ticket', verbose_name='Талон')),
            ],
            options={
                'verbose_name': 'Доставка уведомления',
                'verbose_name_plural': 'Доставки уведомлений',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ticket.called', 'Ticket called')], max_length=50, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP-статус')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='queues.queue', verbose_name='Очередь')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.webhooksubscription', verbose_name='Webhook-подписка')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='queues.ticket', verbose_name='Талон')),
            ],
            options={
                'verbose_name': 'Доставка webhook',
                'verbose_name_plural': 'Доставки webhook',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='clientnotificationsubscription',
            index=models.Index(fields=['queue', 'client', 'channel'], name='notificatio_queue_i_d73d33_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnotificationsubscription',
            index=models.Index(fields=['channel', 'is_active'], name='notificatio_channel_972005_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['company', 'is_active'], name='notificatio_company_0e0f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['queue', 'is_active'], name='notificatio_queue_i_418bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['event_type', 'status'], name='notificatio_event_t_9b15bd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['queue', 'ticket'], name='notificatio_queue_i_9114e9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_type', 'status'], name='notificatio_event_t_f1bcf6_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['queue', 'ticket'], name='notificatio_queue_i_8bd48f_idx'),
        ),
    ]
