# Generated by Codex on 2026-05-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_subscriptions_webhooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationDelivery',
        ),
    ]
