# Generated by Django 5.2.12 on 2026-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delete_notificationdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='event_type',
            field=models.CharField(choices=[('ticket.called', 'Ticket called'), ('ticket.status_changed', 'Ticket status changed')], max_length=50, verbose_name='Тип события'),
        ),
    ]
