services:
  db:
    image: postgres:16
    container_name: qr_app_db
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr_app_backend
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: qr_app_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    depends_on:
      - backend
    ports:
      - "9090:9090"
    restart: unless-stopped

volumes:
  postgres_data:
    name: qr_app_postgres_data
  prometheus_data:
    name: qr_app_prometheus_data
