# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('queues', '0010_ticket_operator'),
        ('users', '0006_user_assigned_queues_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP статус')),
                ('latency_ms', models.FloatField(default=0.0, verbose_name='Задержка, мс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to='companies.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to='companies.company', verbose_name='Компания')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to='users.user', verbose_name='Оператор')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to='queues.queue', verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Журнал API-запроса',
                'verbose_name_plural': 'Журнал API-запросов',
                'indexes': [
                    models.Index(fields=['company', 'created_at'], name='api_log_company_created_idx'),
                    models.Index(fields=['branch', 'created_at'], name='api_log_branch_created_idx'),
                    models.Index(fields=['queue', 'created_at'], name='api_log_queue_created_idx'),
                    models.Index(fields=['operator', 'created_at'], name='api_log_operator_created_idx'),
                    models.Index(fields=['status_code', 'created_at'], name='api_log_status_created_idx'),
                ],
            },
        ),
    ]
