# Generated by Django 5.2.12 on 2026-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('vk_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='VK ID')),
                ('preferred_lang', models.CharField(blank=True, max_length=10, null=True, verbose_name='Предпочитаемый язык')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('branch_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID филиала')),
                ('send_notification', models.BooleanField(default=False, verbose_name='Отправлять уведомления')),
                ('consent_ad', models.BooleanField(default=False, verbose_name='Отправлять рекламу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
