# Generated by Django 5.2.12 on 2026-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обслуживания'),
        ),
    ]
