# Generated by Django 5.2.12 on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_branch_id_user_branch_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='users.user')),
            ],
            options={
                'verbose_name': 'Токен оператора',
                'verbose_name_plural': 'Токены операторов',
            },
        ),
    ]
