# Generated by Django 5.2.12 on 2026-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_queue_called_ticket_timeout_seconds_queue_language_and_more'),
        ('users', '0005_admintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_queues',
            field=models.ManyToManyField(blank=True, related_name='assigned_operators', to='queues.queue', verbose_name='Назначенные очереди'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='ru', max_length=10, verbose_name='Предпочитаемый язык'),
        ),
    ]
