# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_tokens(apps, schema_editor):
    AuthToken = apps.get_model('users', 'AuthToken')

    for model_name in ('OperatorToken', 'AdminToken'):
        OldToken = apps.get_model('users', model_name)
        for old_token in OldToken.objects.all().iterator():
            new_token, _ = AuthToken.objects.update_or_create(
                key=old_token.key,
                defaults={
                    'user_id': old_token.user_id,
                    'expires_at': old_token.expires_at,
                },
            )
            AuthToken.objects.filter(pk=new_token.pk).update(created_at=old_token.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_assigned_queues_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_auth_tokens', to='users.user')),
            ],
            options={
                'verbose_name': 'Токен авторизации',
                'verbose_name_plural': 'Токены авторизации',
            },
        ),
        migrations.RunPython(copy_existing_tokens, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AdminToken',
        ),
        migrations.DeleteModel(
            name='OperatorToken',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='users.user'),
        ),
    ]
